const FLAGS_BY_COUNTRY = {
  'España': '🇪🇸',
  'Portugal': '🇵🇹',
  'Reino Unido': '🇬🇧',
  'Francia': '🇫🇷',
  'Países Bajos': '🇳🇱',
  'Alemania': '🇩🇪',
  'Italia': '🇮🇹',
  'Grecia': '🇬🇷',
  'Turquía': '🇹🇷',
  'Irlanda': '🇮🇪',
  'Dinamarca': '🇩🇰',
  'Noruega': '🇳🇴',
  'Suecia': '🇸🇪',
  'Finlandia': '🇫🇮',
  'Austria': '🇦🇹',
  'Suiza': '🇨🇭',
  'República Checa': '🇨🇿',
  'Polonia': '🇵🇱',
  'Hungría': '🇭🇺',
  'Rusia': '🇷🇺',
  'Estados Unidos': '🇺🇸',
  'Canadá': '🇨🇦',
  'México': '🇲🇽',
  'Colombia': '🇨🇴',
  'Perú': '🇵🇪',
  'Chile': '🇨🇱',
  'Argentina': '🇦🇷',
  'Brasil': '🇧🇷',
  'Japón': '🇯🇵',
  'Corea del Sur': '🇰🇷',
  'China': '🇨🇳',
  'Hong Kong': '🇭🇰',
  'Taiwán': '🇹🇼',
  'Tailandia': '🇹🇭',
  'Singapur': '🇸🇬',
  'Malasia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Filipinas': '🇵🇭',
  'India': '🇮🇳',
  'Emiratos Árabes Unidos': '🇦🇪',
  'Catar': '🇶🇦',
  'Egipto': '🇪🇬',
  'Sudáfrica': '🇿🇦',
  'Australia': '🇦🇺',
  'Nueva Zelanda': '🇳🇿',
};

export function flagFor(countryName) {
  return FLAGS_BY_COUNTRY[countryName] || '🌍';
}
